matrix:
  include:
    - language: android
      jdk: oraclejdk8
      before_install:
        - nvm install 8
        - echo yes | sdkmanager "platforms;android-28"
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
        - export PATH=$HOME/.yarn/bin:$PATH
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - tools
      cache:
        bundler: true
        yarn: true
        directories:
          - example/node_modules
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      before_cache:
        - rm -f example/node_modules/\@react-native-mapbox-gl/
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    - os: osx
      osx_image: xcode10.2
      node_js: 8
      cache:
        bundler: true
        yarn: true
        cocoapods: true
        directories:
          - example/node_modules
          - $HOME/Library/Caches/Homebrew
      before_cache:
        - rm -f example/node_modules/\@react-native-mapbox-gl/
        - brew cleanup
      podfile: example/ios/Podfile

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - cd $TRAVIS_BUILD_DIR/example
  - echo $MAPBOX_ACCESS_TOKEN > ./accesstoken
  - find node_modules -name ".git" -exec rm -r "{}" \; || true
  - rm -rf example/node_modules/\@react-native-mapbox-gl/
  - yarn install
  - echo $TRAVIS_OS_NAME
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      cd $TRAVIS_BUILD_DIR/example/ios
      pod install
      pod update
      gem install xcpretty
    fi
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      cd $TRAVIS_BUILD_DIR/example/ios
      set -o pipefail
      rm -f build
      xcodebuild -arch x86_64 -sdk iphonesimulator12.2  -workspace ./RNMapboxGLExample.xcworkspace -scheme RNMapboxGLExample | xcpretty -c
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      cd $TRAVIS_BUILD_DIR/example/android
      TERM=dumb ./gradlew assemble
    fi
  - cd $TRAVIS_BUILD_DIR
  - yarn global add -g 'jest@24.8.0'
  - yarn install
  - yarn run unittest
